### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by dodona2** [arnoldrobbins/hp#1]
make
yacc -d hp.gram.y 
mv -f y.tab.c hp.gram.c
mv: cannot stat 'y.tab.c': No such file or directory
make: *** [<builtin>: hp.gram.c] Error 1

with: 
yacc --version
bison (GNU Bison) 3.4.1
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2019 Free Software Foundation, Inc.

**Comment by arnoldrobbins** [comment]
What system are you on?  On Ubuntu 18.04, there's no problem.

What happens if you edit the makefile to use `bison -y` instead of `yacc`?

Thanks.

**Comment by dodona2** [comment]
- Fedora release 31 (Thirty One)

- bison -y hp.gram.y
  hp.gram.y:18.1-5: warning: POSIX Yacc does not support %term [-Wyacc]
   18 | %term DOT DIGIT BIGP LITTLEP PLUS MINUS STAR SLASH PERCENT POW
          | ^~~~~
   hp.gram.y:19.1-5: warning: POSIX Yacc does not support %term [-Wyacc]
      19 | %term AND OR NOT EQ LT GT LE GE BIGD LITTLED QUIT CHANGESIGN

- I checked out berkely yacc and it works.
     http://invisible-island.net/byacc/
     https://en.wikipedia.org/wiki/Berkeley_Yacc

**Comment by arnoldrobbins** [comment]
I have updated the Makefile to invoke bison directly but with the -y and -Wno-yacc options so that it builds quietly.  Thanks for reporting the issue. Closing it out.

**Comment by dodona2** [comment]
**OK. Thanks Arnold!**

>git pull
   ....  3 files changed, 13 insertions(+), 3 deletions(-)

> make
bison -y -Wno-yacc -d hp.gram.y 
mv -f y.tab.c hp.gram.c
cc -O   -c -o hp.gram.o hp.gram.c
cc -O hp.o hp.gram.o  -lm -o hp
rm hp.gram.c
